---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: drives, expand, free, capacity, existing, pool, volume, group, expansion, causes, additional, include, data, remain, accessible, operation 
summary: Você pode adicionar unidades para expandir a capacidade livre em um pool ou grupo de volumes existente. A expansão faz com que a capacidade livre adicional seja incluída no pool ou no grupo de volumes. Você pode usar essa capacidade gratuita para criar volumes adicionais. Os dados nos volumes permanecem acessíveis durante esta operação. 
---
= Adicionar capacidade a um pool ou grupo de volumes
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar unidades para expandir a capacidade livre em um pool ou grupo de volumes existente. A expansão faz com que a capacidade livre adicional seja incluída no pool ou no grupo de volumes. Você pode usar essa capacidade gratuita para criar volumes adicionais. Os dados nos volumes permanecem acessíveis durante esta operação.

.Antes de começar
* As unidades devem estar em um status ideal.
* As unidades devem ter o mesmo tipo de unidade (HDD ou SSD).
* O pool ou grupo de volume deve estar em um status ideal.
* Se o pool ou grupo de volumes contiver todas as unidades com capacidade segura, adicione apenas unidades com capacidade segura para continuar a usar as habilidades de criptografia das unidades com capacidade segura.
+
As unidades com capacidade segura podem ser unidades com criptografia total de disco (FDE) ou unidades FIPS (Federal Information Processing Standard).



.Sobre esta tarefa
Para pools, você pode adicionar um máximo de 60 unidades de cada vez ou até 60 unidades por meio de múltiplos de 5 TB. Para grupos de volumes, você pode adicionar um máximo de duas unidades de cada vez. Se for necessário adicionar mais do que o número máximo de unidades, repita o procedimento. (Um pool não pode conter mais unidades do que o limite máximo para um storage de armazenamento.)

[NOTE]
====
Com a adição de unidades, sua capacidade de preservação pode precisar ser aumentada. Você deve considerar aumentar a capacidade reservada após uma operação de expansão.

====
[NOTE]
====
Evite usar unidades que são capazes de garantia de dados (DA) para adicionar capacidade a um pool ou grupo de volume que não é capaz de DA. O pool ou o grupo de volumes não podem aproveitar as capacidades da unidade capaz de DA. Considere usar unidades que não são capazes de DA nesta situação.

====
.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Selecione o pool ou grupo de volumes ao qual deseja adicionar unidades e clique em *Adicionar capacidade*.
+
A caixa de diálogo *Adicionar capacidade* é exibida. Somente as unidades não atribuídas compatíveis com o pool ou grupo de volumes são exibidas.

. Em *Selecione unidades para adicionar capacidade...*, selecione uma ou mais unidades que você deseja adicionar ao pool ou grupo de volumes existente.
+
O firmware do controlador organiza as unidades não atribuídas com as melhores opções listadas na parte superior. A capacidade total gratuita adicionada ao pool ou grupo de volumes aparece abaixo da lista em *capacidade total selecionada*.

+
.Detalhes do campo
[%collapsible]
====
[cols="1a,3a"]
|===
| Campo | Descrição 


 a| 
Gaveta
 a| 
Indica a localização do compartimento da unidade.



 a| 
Baía
 a| 
Indica a localização do compartimento da unidade.



 a| 
Capacidade (GiB)
 a| 
Indica a capacidade da unidade.

** Sempre que possível, selecione unidades que tenham uma capacidade igual às capacidades das unidades atuais no pool ou grupo de volumes.
** Se você precisar adicionar unidades não atribuídas com uma capacidade menor, lembre-se de que a capacidade utilizável de cada unidade atualmente no pool ou grupo de volumes será reduzida. Portanto, a capacidade da unidade é a mesma em todo o pool ou grupo de volumes.
** Se você precisar adicionar unidades não atribuídas com uma capacidade maior, lembre-se de que a capacidade utilizável das unidades não atribuídas adicionadas será reduzida para que elas correspondam às capacidades atuais das unidades no pool ou grupo de volumes.




 a| 
Com capacidade segura
 a| 
Indica se a unidade é segura.

** Você pode proteger seu pool ou grupo de volumes com o recurso Segurança da unidade, mas todas as unidades devem ser seguras para usar esse recurso.
** Você pode misturar unidades com capacidade segura e não seguras, mas as habilidades de criptografia das unidades com capacidade segura não podem ser usadas.
** As unidades com capacidade segura podem ser unidades com criptografia total de disco (FDE) ou unidades FIPS (Federal Information Processing Standard).




 a| 
DA capaz
 a| 
Indica se a unidade é capaz de Garantia de dados (DA).

** O uso de unidades que não são capazes de garantia de dados (DA) para adicionar capacidade a um pool ou grupo de volume compatível com DA não é recomendado. O pool ou grupo de volumes não tem mais recursos DA e você não tem mais a opção de ativar DA em volumes recém-criados dentro do pool ou grupo de volumes.
** O uso de unidades que são capazes de garantia de dados (DA) para adicionar capacidade a um pool ou grupo de volume que não é capaz de DA não é recomendado, porque esse pool ou grupo de volume não pode tirar proveito dos recursos da unidade capaz de DA (os atributos da unidade não correspondem). Considere usar unidades que não são capazes DE DA nesta situação.




 a| 
DULBE capaz
 a| 
Indica se a unidade tem a opção de erro de bloco lógico desalocado ou não escrito (DULBE). DULBE é uma opção nas unidades NVMe que permite que um storage array EF600D produza blocos que façam parte de um volume. A desalocação de blocos em uma unidade pode reduzir significativamente o tempo necessário para inicializar volumes. Além disso, os hosts podem desalocar blocos lógicos no volume usando o comando NVMe Dataset Management.

|===
====
. Clique em *Add*.


Se você estiver adicionando unidades a um pool ou grupo de volumes, uma caixa de diálogo de confirmação será exibida se você selecionar uma unidade que faça com que o pool ou grupo de volumes não tenha mais um ou mais dos seguintes atributos:

* Proteção contra perda de prateleira
* Proteção contra perda de gaveta
* Capacidade de encriptação total do disco
* Capacidade de garantia de dados
* Capacidade DULBE


Para continuar, clique em *Yes*; caso contrário, clique em *Cancel*.

.Resultados
Depois de adicionar as unidades não atribuídas a um pool ou grupo de volumes, os dados em cada volume do pool ou grupo de volumes são redistribuídos para incluir as unidades adicionais.
