---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full 
summary: Você pode alterar as configurações de um volume de par espelhado para ajustar o ponto percentual no qual o System Manager envia uma notificação de alerta quando a capacidade reservada para um volume de par espelhado estiver quase cheia. 
---
= Altere as configurações de capacidade reservada para um volume de par espelhado
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume de par espelhado para ajustar o ponto percentual no qual o System Manager envia uma notificação de alerta quando a capacidade reservada para um volume de par espelhado estiver quase cheia.

.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Selecione a guia *capacidade reservada*.
. Selecione o volume do par espelhado que você deseja editar e clique em *Exibir/Editar configurações*.
+
A caixa de diálogo *Configurações de capacidade reservada do volume do par espelhado* é exibida.

. Altere as configurações de capacidade reservada para o volume do par espelhado, conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="1a,3a"]
|===
| Definição | Descrição 


 a| 
Alerta-me quando...
 a| 
Use a caixa giratório para ajustar o ponto percentual no qual o System Manager envia uma notificação de alerta quando a capacidade reservada para um par espelhado estiver quase cheia.

Quando a capacidade reservada para o par espelhado excede o limite especificado, o System Manager envia um alerta, permitindo que você aumente a capacidade reservada.


NOTE: Alterar a configuração Alerta para um par espelhado altera a configuração Alerta para todos os pares espelhados que pertencem ao mesmo grupo de consistência de espelho.



 a| 
Política de capacidade reservada completa
 a| 
Você pode escolher uma das seguintes políticas:

** *Limpar imagem de snapshot mais antiga* – o System Manager limpa automaticamente a imagem de snapshot mais antiga do grupo de consistência, que libera a capacidade reservada do membro para reutilização dentro do grupo.
** *Rejeitar gravações no volume base* – quando a capacidade reservada atinge sua porcentagem máxima definida, o System Manager rejeita qualquer solicitação de gravação de e/S para o volume base que acionou o acesso à capacidade reservada.


|===
====
. Clique em *Salvar* para aplicar suas alterações.


.Resultado
O System Manager altera as configurações de capacidade reservada para o volume do membro, bem como as configurações de capacidade reservada para todos os volumes do membro no grupo consistência.
