---
permalink: sm-storage/create-pool-manually.html 
sidebar: sidebar 
keywords: create, pool, manually, set, candidates, auto configuration, feature, provide, meet, needs, logical, storage, capacity, necessary, individual, volumes, use, host, application 
summary: 'Você pode criar um pool manualmente (a partir de um conjunto de candidatos) se o recurso Configuração automática do pool não fornecer um pool que atenda às suas necessidades. Um pool fornece a capacidade de storage lógica necessária a partir da qual você pode criar volumes individuais que podem ser usados para hospedar seus aplicativos.' 
---
= Criar pool manualmente
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um pool manualmente (a partir de um conjunto de candidatos) se o recurso Configuração automática do pool não fornecer um pool que atenda às suas necessidades. Um pool fornece a capacidade de storage lógica necessária a partir da qual você pode criar volumes individuais que podem ser usados para hospedar seus aplicativos.

.Antes de começar
* Você deve ter um mínimo de 11 unidades com o mesmo tipo de unidade (HDD ou SSD).
* A proteção contra perda de gaveta exige que as unidades que compõem o pool estejam localizadas em pelo menos seis compartimentos de unidades diferentes e não haja mais do que duas unidades em um único compartimento de unidades.
* A proteção contra perda de gaveta exige que as unidades que compõem o pool estejam localizadas em pelo menos cinco gavetas diferentes e o pool inclua um número igual de prateleiras de unidades de cada gaveta.
* Ao configurar um storage array EF600, verifique se cada controlador tem acesso a um número igual de unidades nos primeiros 12 slots e a um número igual de unidades nos últimos 12 slots. Essa configuração ajuda os controladores a usar os dois barramentos PCIe do lado da unidade de forma mais eficaz. Atualmente o System Manager permite a seleção de unidades no recurso Avançado ao criar um grupo de volumes. Para a criação de pool, recomenda-se usar todas as unidades no storage de armazenamento.


.Passos
. Selecione menu:armazenamento[pools & grupos de volume].
. Clique em menu:criar[Pool].
+
A caixa de diálogo *Create Pool* é exibida.

. Digite um nome para o pool.
. *Opcional:* se você tiver mais de um tipo de unidade em sua matriz de armazenamento, selecione o tipo de unidade que você deseja usar.
+
A tabela de resultados lista todos os pools possíveis que você pode criar.

. Selecione o candidato ao pool que você deseja usar com base nas seguintes caraterísticas e clique em *criar*.


[cols="2*"]
|===
| Característica | Utilização 


 a| 
Capacidade livre
 a| 
Mostra a capacidade livre do candidato à pool em GiB. Selecione um candidato a pool com a capacidade para as necessidades de armazenamento do seu aplicativo.

A capacidade de preservação (sobressalente) também é distribuída em toda a piscina e não faz parte do valor da capacidade livre.



 a| 
Total de unidades
 a| 
Mostra o número de unidades disponíveis no candidato ao pool.

O System Manager reserva automaticamente o máximo de unidades possível para a capacidade de preservação (para cada seis unidades em um pool, o System Manager reserva uma unidade para a capacidade de preservação).

Quando ocorre uma falha de unidade, a capacidade de preservação é utilizada para manter os dados reconstruídos.



 a| 
Com capacidade segura
 a| 
Indica se esse candidato a pool é composto inteiramente de unidades com capacidade de segurança, que podem ser unidades com criptografia total de disco (FDE) ou unidades FIPS (Federal Information Processing Standard).

* Você pode proteger seu pool com o Drive Security, mas todas as unidades devem ser seguras para usar esse recurso.
* Se você quiser criar um pool apenas FDE, procure *Sim - FDE* na coluna compatível com segurança. Se você quiser criar um pool somente FIPS, procure *Yes - FIPS* na coluna Secure-Capable.
* Você pode criar um pool composto de unidades que podem ou não ser seguras ou que são uma combinação de níveis de segurança. Se as unidades no pool incluírem unidades que não são seguras, você não poderá tornar o pool seguro.




 a| 
Ativar segurança?
 a| 
Fornece a opção para ativar o recurso de Segurança da Unidade com unidades com capacidade segura. Se o pool for seguro e você tiver criado uma chave de segurança, poderá ativar a segurança selecionando a caixa de seleção.

[NOTE]
====
A única maneira de remover o Drive Security depois de ativado é excluir o pool e apagar as unidades.

====


 a| 
DA capaz
 a| 
Indica se a Garantia de dados (DA) está disponível para este candidato a pool. O DA verifica e corrige erros que podem ocorrer à medida que os dados são transferidos através dos controladores para as unidades.

Se você quiser usar DA, selecione um pool que seja capaz de DA. Esta opção só está disponível quando a funcionalidade DA tiver sido ativada.

Um pool pode conter unidades que são capazes de DA ou não, mas todas as unidades devem ser capazes DE DA para você usar esse recurso.



 a| 
Proteção contra perda de prateleira
 a| 
Mostra se a proteção contra perda de prateleira está disponível.

A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool se houver perda total de comunicação com um único compartimento de unidade.



 a| 
Proteção contra perda de gaveta
 a| 
Mostra se a proteção contra perda de gaveta está disponível, que é fornecida somente se você estiver usando uma prateleira de unidade que contém gavetas.

A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool se ocorrer uma perda total de comunicação com uma única gaveta em um compartimento de unidades.

|===