---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: create, volumes, using, either, pool, group, selection, depend, primarily, key, storage, requirements, expect, workload, performance, data, protection 
summary: Você pode criar volumes usando um pool ou um grupo de volumes. A melhor seleção depende principalmente dos principais requisitos de storage, como o workload de e/S esperado, os requisitos de performance e os requisitos de proteção de dados. 
---
= Decida se deseja usar um pool ou um grupo de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar volumes usando um pool ou um grupo de volumes. A melhor seleção depende principalmente dos principais requisitos de storage, como o workload de e/S esperado, os requisitos de performance e os requisitos de proteção de dados.



== Razões para escolher um pool ou grupo de volume

*Escolha uma piscina*

* Se você precisar de reconstruções de unidades mais rápidas e administração simplificada de storage, exija thin volumes e/ou tenha um workload altamente aleatório.
* Se você quiser distribuir os dados para cada volume aleatoriamente em um conjunto de unidades que compõem o pool.
+
Não é possível definir ou alterar o nível RAID de pools ou volumes nos pools. Os pools usam RAID nível 6.



*Escolha um grupo de volume*

* Se você precisar de largura de banda máxima do sistema, a capacidade de ajustar as configurações de storage e um workload altamente sequencial.
* Se você quiser distribuir os dados entre as unidades com base em um nível RAID. Você pode especificar o nível RAID ao criar o grupo de volumes.
* Se você quiser gravar os dados para cada volume sequencialmente no conjunto de unidades que compõem o grupo de volumes.


[NOTE]
====
Como os pools podem coexistir com grupos de volume, um storage array pode conter pools e grupos de volume.

====


== Diferenças de recursos entre pools e grupos de volume

A tabela a seguir fornece uma comparação de recursos entre grupos de volume e pools.

[cols="3*"]
|===
| Utilização | Piscina | Grupo de volume 


 a| 
Carga de trabalho aleatória
 a| 
Melhor
 a| 
Bom



 a| 
Workload sequencial
 a| 
Bom
 a| 
Melhor



 a| 
Tempo de recriação da unidade
 a| 
Mais rápido
 a| 
Mais lento



 a| 
Desempenho (modo ideal)
 a| 
Bom: Melhor para bloco pequeno, carga de trabalho aleatória.
 a| 
Bom: Melhor para cargas de trabalho sequenciais e em blocos grandes



 a| 
Desempenho (modo de recriação da unidade)
 a| 
Melhor: Geralmente melhor que RAID 6
 a| 
Degradada: Queda de até 40% no desempenho



 a| 
Várias falhas de unidade
 a| 
Maior proteção de dados: Reconstruções com maior rapidez e prioridade
 a| 
Menos proteção de dados: Reconstruções lentas, maior risco de perda de dados



 a| 
Adicionar unidades
 a| 
Mais rápido: Adicionar à piscina em tempo real
 a| 
Mais lento: Requer operação de expansão de capacidade dinâmica



 a| 
Suporte a volumes finos
 a| 
Sim
 a| 
Não



 a| 
Suporte a disco de estado sólido (SSD)
 a| 
Sim
 a| 
Sim



 a| 
Administração simplificada
 a| 
Sim: Não hot spares ou configurações RAID para configurar
 a| 
Não: Deve alocar hot spares, configurar RAID



 a| 
Desempenho ajustável
 a| 
Não
 a| 
Sim

|===