---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: Você deve configurar o storage array com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Proteção por senha do administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o storage array com uma senha de administrador para protegê-lo contra acesso não autorizado.



== Definir uma palavra-passe de administrador

A definição de uma palavra-passe de administrador para a sua matriz de armazenamento protege-a de utilizadores que executam comandos destrutivos sem saber ou maliciosamente. É necessário definir uma palavra-passe de administrador quando iniciar o System Manager pela primeira vez.

Há uma senha de administrador que é compartilhada entre todos os usuários. Qualquer usuário que tenha essa senha pode fazer alterações de configuração no storage array, como adicionar, alterar ou remover objetos ou configurações.



== Introduzir a sua palavra-passe

O sistema solicita a senha apenas uma vez durante uma única sessão de gerenciamento. Uma sessão expira após 20 minutos de inatividade, altura em que tem de introduzir novamente a palavra-passe.

Se outro usuário que gerencia o mesmo storage array de outro cliente de gerenciamento alterar a senha enquanto sua sessão estiver em andamento, você será solicitado a digitar uma senha da próxima vez que tentar uma operação de configuração ou uma operação de exibição.

Por razões de segurança, você pode tentar inserir uma senha apenas cinco vezes antes que o storage de armazenamento entre em um estado de "bloqueio". Nesse estado, o storage array rejeitará tentativas subsequentes de senha. Você deve esperar 10 minutos para que a matriz de armazenamento seja redefinida para um estado "normal" antes de tentar digitar uma senha novamente.



== Remoção de unidades com proteção por senha

A senha é armazenada em uma área reservada de cada unidade na matriz de armazenamento. Se você remover todas as unidades de um storage array, sua senha não funcionará mais. Para corrigir essa condição, reinstale uma das unidades originais no storage de armazenamento.



== Remoção da proteção por senha

Se você não quiser mais ter comandos protegidos por senha, digite a senha atual do administrador e deixe as caixas de texto da nova senha em branco.

[NOTE]
====
Executar comandos de configuração em um storage array pode causar sérios danos, incluindo perda de dados. Por esse motivo, você sempre deve definir uma senha de administrador para o storage array. Use uma senha de administrador longa com pelo menos 15 carateres alfanuméricos para aumentar a segurança.

====