---
permalink: um-manage/storage-array-status.html 
sidebar: sidebar 
keywords: storage, array, status, 
summary: Quando você abre o SANtricity Unified Manager, a comunicação com cada storage array é estabelecida e o status de cada storage array é exibido. 
---
= Status do storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você abre o SANtricity Unified Manager, a comunicação com cada storage array é estabelecida e o status de cada storage array é exibido.

Você pode exibir o status do storage array e o status da conexão entre o Web Services Proxy e esse storage array.

[cols="1a,1a"]
|===
| Estado | Indica 


 a| 
Ideal
 a| 
O storage array está em um estado ideal. Não há problemas de certificado e a senha é válida.



 a| 
Palavra-passe inválida
 a| 
Foi fornecida uma palavra-passe inválida da matriz de armazenamento.



 a| 
Certificado não fidedigno
 a| 
Uma ou mais conexões com o storage não são confiáveis porque o certificado HTTPS é autoassinado e não foi importado, ou o certificado é assinado pela CA e os certificados raiz e intermediário da CA não foram importados.



 a| 
Precisa de atenção
 a| 
Há um problema com o storage array que requer a sua intervenção para corrigi-lo.



 a| 
Bloqueio
 a| 
O storage array está em um estado bloqueado.



 a| 
Desconhecido
 a| 
O storage array nunca foi contatado. Isso pode acontecer quando o Web Services Proxy está sendo iniciado e ainda não entrou em Contato com o storage array, ou o storage está offline e nunca foi contatado desde que o Web Services Proxy foi iniciado.



 a| 
Offline
 a| 
O Web Services Proxy já havia contatado o storage array, mas agora perdeu toda a conexão com ele.

|===