---
permalink: sm-settings/add-community-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: add up, community, snmp traps 
summary: Você pode adicionar até 256 nomes de comunidade para traps SNMP. 
---
= Adicione nomes de comunidade para traps SNMP
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar até 256 nomes de comunidade para traps SNMP.

.Antes de começar
O(s) nome(s) da comunidade tem de ser criado(s). O nome da comunidade, que é uma cadeia de carateres que funciona como uma senha para os servidores de rede, é normalmente criado por um administrador de rede. Consiste apenas em carateres ASCII imprimíveis.

.Passos
. Selecione *menu:Configurações[Alertas]*.
. Selecione a guia *SNMP*.
+
Os destinos da armadilha e os nomes da comunidade aparecem na tabela.

. Selecione *Configurar Comunidades*.
+
A caixa de diálogo Configurar Comunidades é aberta.

. Selecione *Adicionar outra comunidade*.
. Digite o novo nome da comunidade e clique em *Salvar*.


.Resultados
O novo nome da comunidade aparece na guia *SNMP* da página *Alertas*.
