---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: secure, enable, storage array, appropriate, importing, new storage, drive 
summary: Se você mover unidades habilitadas para segurança de um storage array para outro, será necessário importar a chave de segurança apropriada para o novo storage array. A importação da chave desbloqueia os dados nas unidades. 
---
= Desbloqueie unidades usando uma chave de segurança
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você mover unidades habilitadas para segurança de um storage array para outro, será necessário importar a chave de segurança apropriada para o novo storage array. A importação da chave desbloqueia os dados nas unidades.

.Antes de começar
* A matriz de armazenamento de destino (onde você está movendo as unidades) já deve ter uma chave de segurança configurada. As unidades migradas serão recodificadas para o storage de armazenamento de destino.
* Você deve saber a chave de segurança que está associada às unidades que deseja desbloquear.
* O arquivo de chave de segurança está disponível no cliente de gerenciamento (o sistema com um navegador usado para acessar o System Manager). Se você estiver movendo as unidades para um storage array gerenciado por um sistema diferente, será necessário mover o arquivo de chave de segurança para esse cliente de gerenciamento.


.Sobre esta tarefa
Esta tarefa descreve como desbloquear dados em unidades habilitadas com segurança que foram removidas de um storage array e reinstaladas em outro. Uma vez que o array descobre as unidades, uma condição "precisa de atenção" aparece junto com um status de "chave de segurança necessária" para essas unidades relocadas. Você pode desbloquear os dados da unidade importando sua chave de segurança para a matriz de armazenamento. Durante este processo, selecione o ficheiro da chave de segurança e introduza a frase-passe da chave.

[NOTE]
====
A frase-passe não é a mesma que a senha de administrador do storage array.

====
Se outras unidades habilitadas para segurança estiverem instaladas no novo storage array, elas poderão usar uma chave de segurança diferente da que você está importando. Durante o processo de importação, a chave de segurança antiga é usada apenas para desbloquear os dados das unidades que você está instalando. Quando o processo de desbloqueio é bem-sucedido, as unidades recém-instaladas são recodificadas para a chave de segurança da matriz de armazenamento de destino.

.Passos
. Selecione menu:Definições[sistema].
. Em *Gerenciamento de chaves de segurança*, selecione *desbloquear unidades seguras*.
+
A caixa de diálogo desbloquear unidades seguras abre-se. Todas as unidades que exigem uma chave de segurança são mostradas na tabela.

. *Opcional:* passe o Mouse sobre um número de unidade para ver a localização da unidade (número de prateleira e número de compartimento).
. Clique em *Procurar* e selecione o arquivo de chave de segurança que corresponde à unidade que deseja desbloquear.
+
O arquivo de chave selecionado aparece na caixa de diálogo.

. Introduza a frase-passe associada a este ficheiro de chave.
+
Os carateres inseridos são mascarados.

. Clique em *Unlock*.
+
Se a operação de desbloqueio for bem-sucedida, a caixa de diálogo exibe: "As unidades seguras associadas foram desbloqueadas."



.Resultados
Quando todas as unidades estiverem bloqueadas e, em seguida, desbloqueadas, cada controlador na matriz de armazenamento será reiniciado. No entanto, se já houver algumas unidades desbloqueadas no storage de armazenamento de destino, os controladores não serão reinicializados.
