---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: ca signed certificate, secure communication, controller, browser, system manager 
summary: Você pode obter certificados assinados pela CA para comunicações seguras entre os controladores e o navegador usado para acessar o System Manager. 
---
= Use certificados assinados pela CA para controladores
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode obter certificados assinados pela CA para comunicações seguras entre os controladores e o navegador usado para acessar o System Manager.

.Antes de começar
* Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções do certificado não aparecem.


.Sobre esta tarefa
O uso de certificados assinados pela CA é um procedimento de três etapas.



== Passo 1: Complete e envie um CSR para os controladores

Primeiro, você deve gerar um arquivo de solicitação de assinatura de certificado (CSR) para cada controlador no storage array e, em seguida, enviar o(s) arquivo(s) para uma autoridade de certificação (CA).

.Antes de começar
* Você deve saber o endereço IP ou o nome DNS de cada controlador.


.Sobre esta tarefa
O CSR fornece informações sobre a sua organização, o endereço IP ou o nome DNS do controlador e um par de chaves que identifica o servidor Web no controlador. Durante esta tarefa, um arquivo CSR é gerado se houver apenas um controlador na matriz de armazenamento e dois arquivos CSR se houver dois controladores.

[CAUTION]
====
Não gere um novo CSR após o envio para a CA. Quando você gera um CSR, o sistema cria um par de chaves privadas e públicas. A chave pública faz parte da CSR, enquanto a chave privada é mantida no keystore. Quando você recebe os certificados assinados e os importa para o keystore, o sistema garante que as chaves privadas e públicas sejam o par original. Portanto, você não deve gerar um novo CSR depois de enviar um para a CA. Se o fizer, os controladores geram novas chaves e os certificados que você recebe da CA não funcionarão.

====
.Passos
. Selecione *menu:Configurações[certificados]*.
. Na guia *Array Management*, selecione *Complete CSR*.
+
[NOTE]
====
Se você vir uma caixa de diálogo solicitando que você aceite um certificado autoassinado para o segundo controlador, clique em *aceitar certificado autoassinado* para continuar.

====
. Insira as seguintes informações e clique em *Next*:
+
** *Organização* -- o nome completo e legal de sua empresa ou organização. Inclua sufixos, como Inc. Ou Corp.
** * Unidade organizacional (opcional) * -- a divisão da sua organização que está a lidar com o certificado.
** *Cidade/localidade* -- a cidade onde seu storage array ou negócio está localizado.
** *Estado/região (opcional)* -- o estado ou a região onde o storage ou a empresa está localizado.
** *Código ISO do país* -- o código ISO de dois dígitos do seu país (Organização Internacional para Padronização), como os EUA.


+
[CAUTION]
====
Alguns campos podem ser pré-preenchidos com as informações apropriadas, como o endereço IP do controlador. Não altere valores pré-preenchidos a menos que você tenha certeza de que eles estão incorretos. Por exemplo, se você ainda não concluiu um CSR, o endereço IP do controlador é definido como ""localhost". Neste caso, você deve alterar ""localhost"" para o nome DNS ou endereço IP do controlador.

====
. Verifique ou insira as seguintes informações sobre o controlador A no storage array:
+
** *Controller Um nome comum* -- o endereço IP ou o nome DNS do controlador A é exibido por padrão. Certifique-se de que este endereço está correto; ele deve corresponder exatamente ao que você digita para acessar o System Manager no navegador.
** *Controller Um endereço IP alternativo* -- se o nome comum for um endereço IP, você pode opcionalmente inserir quaisquer endereços IP adicionais ou aliases para o controlador A. para várias entradas, use um formato delimitado por vírgulas.
** *Controller (controlador) De nomes DNS alternativos* -- se o nome comum for um nome DNS, insira quaisquer nomes DNS adicionais para o controlador A. para várias entradas, use um formato delimitado por vírgulas. Se não houver nomes DNS alternativos, mas você inseriu um nome DNS no primeiro campo, copie esse nome aqui. Se a matriz de armazenamento tiver apenas um controlador, o botão *Finish* estará disponível. Se a matriz de armazenamento tiver dois controladores, o botão *Next* estará disponível.


+
[NOTE]
====
Não clique no link *Ignorar esta etapa* quando você estiver criando inicialmente uma solicitação CSR. Este link é fornecido em situações de recuperação de erros. Em casos raros, uma solicitação CSR pode falhar em um controlador, mas não no outro. Este link permite que você ignore a etapa para criar uma solicitação CSR no controlador A, se já estiver definida, e continue para a próxima etapa para recriar uma solicitação CSR no controlador B.

====
. Se houver apenas um controlador, clique em *Finish*. Se houver dois controladores, clique em *Next* para inserir informações para o controlador B (o mesmo que acima) e, em seguida, clique em *Finish*.
+
Para um único controlador, um ficheiro CSR é transferido para o seu sistema local. Para controladores duplos, são transferidos dois ficheiros CSR. A localização da pasta do download depende do seu navegador.

. Localize o(s) ficheiro(s) CSR transferido(s). A localização da pasta depende do seu navegador.
. Envie o(s) arquivo(s) CSR para uma CA e solicite certificados assinados no formato PEM.
. Aguarde até que a CA devolva os certificados e, em seguida, vá para <<Etapa 2: Importar certificados assinados para controladores>>.




== Etapa 2: Importar certificados assinados para controladores

Depois de receber certificados assinados, importe os arquivos para os controladores.

.Antes de começar
* A CA retornou arquivos de certificado assinados.
* Os ficheiros estão disponíveis no seu sistema local.
* Se a CA forneceu um certificado encadeado (por exemplo, um arquivo .p7b), você deve descompactar o arquivo encadeado em arquivos individuais: O certificado raiz, um ou mais certificados intermediários e os certificados de servidor que identificam os controladores. Você pode usar o utilitário Windows `certmgr` para descompactar os arquivos (clique com o botão direito do Mouse e selecione *menu:todas as tarefas[Exportar]*). Quando as exportações estiverem concluídas, um arquivo CER é exibido para cada arquivo de certificado na cadeia.


.Sobre esta tarefa
Esta tarefa descreve como carregar os ficheiros de certificado.

.Passos
. Selecione *menu:Configurações[certificados]*.
. Na guia *Array Management*, selecione *Import*.
+
Abre-se uma caixa de diálogo para importar o(s) ficheiro(s) de certificado.

. Clique nos botões *Browse* para selecionar primeiro os arquivos raiz e intermediário e, em seguida, selecione cada certificado de servidor para os controladores. Os arquivos raiz e intermediário são os mesmos para ambos os controladores. Apenas os certificados de servidor são exclusivos para cada controlador.
+
Os nomes dos arquivos são exibidos na caixa de diálogo.

. Clique em *Importar*.
+
Os arquivos são carregados e validados.



.Resultados
A sessão é terminada automaticamente. Você deve fazer login novamente para que o(s) certificado(s) entre em vigor. Quando você faz login novamente, o novo certificado assinado pela CA é usado para sua sessão.
