---
permalink: um-certificates/why-cant-i-log-in-unified.html 
sidebar: sidebar 
keywords: receive, error, attempt, santricity, unified, manager, causes 
summary: Se você receber um erro ao tentar fazer login no Gerenciador Unificado do SANtricity, revise essas possíveis causas. 
---
= Por que não consigo fazer login?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você receber um erro ao tentar fazer login no Gerenciador Unificado do SANtricity, revise essas possíveis causas.

Erros de login no Unified Manager podem ocorrer por um destes motivos:

* Introduziu um nome de utilizador ou palavra-passe incorreto.
* Você não tem Privileges suficiente.
* O servidor de diretório (se configurado) pode estar indisponível. Se for esse o caso, tente fazer login com uma função de usuário local.
* Tentou iniciar sessão sem sucesso várias vezes, o que acionou o modo de bloqueio. Aguarde 10 minutos para voltar a iniciar sessão.


Erros de login em um storage array remoto para tarefas de espelhamento podem ocorrer por um destes motivos:

* Introduziu uma palavra-passe incorreta.
* Tentou iniciar sessão sem sucesso várias vezes, o que acionou o modo de bloqueio. Aguarde 10 minutos para iniciar sessão novamente.
* O número máximo de conexões de cliente usadas no controlador foi atingido. Verifique se há vários usuários ou clientes.

