---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: configure, santricity, unified, manager, administrator, password, protect, unauthorized, access 
summary: Você deve configurar o SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Proteção por senha do administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado.



== Definir uma palavra-passe de administrador

A definição de uma palavra-passe de administrador protege o software de utilizadores que executam comandos destrutivos sem saber ou maliciosamente. É necessário definir uma senha de administrador ao iniciar o Unified Manager pela primeira vez.

Há uma senha de administrador que é compartilhada entre todos os usuários. Qualquer usuário que tenha essa senha pode fazer alterações de configuração nos sistemas de armazenamento.



== Introduzir a sua palavra-passe

O software solicita a senha apenas uma vez durante uma única sessão de gerenciamento. Uma sessão expira após 30 minutos de inatividade por padrão, e nesse momento, você deve digitar a senha novamente. Se desejar, você pode ajustar o tempo limite da sessão.

Se outro utilizador aceder ao software a partir de outro cliente de gestão e alterar a palavra-passe enquanto a sessão estiver em curso, ser-lhe-á pedida uma palavra-passe da próxima vez que tentar uma operação de configuração ou uma operação de visualização.

Por razões de segurança, você pode tentar inserir uma senha apenas cinco vezes antes que o software entre em um estado de "bloqueio". Neste estado, o software rejeita tentativas subsequentes de senha. Tem de esperar 10 minutos para repor o estado "normal" antes de tentar introduzir novamente uma palavra-passe.
