---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: update, passwords, use, viewing, access, storage, array, santricity, unified, manager 
summary: Você pode atualizar as senhas usadas para visualizar e acessar matrizes de armazenamento no Gerenciador Unificado do SANtricity. 
---
= Altere as senhas do storage array
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar as senhas usadas para visualizar e acessar matrizes de armazenamento no Gerenciador Unificado do SANtricity.

.Antes de começar
* Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de armazenamento.
* Você deve saber a senha atual para o storage array, que é definido no Gerenciador do sistema do SANtricity.


.Sobre esta tarefa
Nesta tarefa, insira a senha atual de um storage array para que você possa acessá-lo no Unified Manager. Isso pode ser necessário se a senha do array tiver sido alterada no System Manager e, agora, ela também deve ser alterada no Unified Manager.

.Passos
. Na página *Gerenciar*, selecione um ou mais storages.
. Selecione menu:tarefas incomuns[fornecer senhas de storage de armazenamento].
. Insira a senha ou as senhas de cada matriz de armazenamento e clique em *Salvar*.

